name: Windows package build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest  # Changed to Windows runner

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel pyinstaller  # Include pyinstaller for building executables
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed PasswordGenerator.py  # Replace with your actual main script if different

    - name: Upload Executable artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/*.exe
close_pull_request_job:
  if: github.event_name == 'pull_request' && github.event.action == 'closed'
  runs-on: ubuntu-latest
  name: Close Pull Request Job
  steps:
    - name: Check if PR is Merged
      id: check_pr_merged
      run: |
        if [ ${{ github.event.pull_request.merged }} == true ]; then
          echo "PR_MERGED=true" >> $GITHUB_ENV
        else
          echo "PR_MERGED=false" >> $GITHUB_ENV
        fi

    - name: Close Pull Request
      if: env.PR_MERGED == 'true'
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets}}
        action: "close"
    
    - name: PR Closed but not Merged
      if: env.PR_MERGED == 'false'
      run: echo "Pull request closed without merge. No further action taken."
