name: Create PR to Solve an Issue Using ChatGPT

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creates a PR to solve an issue using ChatGPT
        uses: alexanmtz/AIPR@v0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Add any other required inputs here

      # Additional steps can be added here if needed
