name: Mac package build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest wheel py2app
          pip install -r requirements.txt

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Build macOS app with py2app
        run: |
          python setup.py py2app
      - name: Upload macOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-application
          path: dist/*.app
