name: Build Artifacts and Handle Closed PRs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest wheel  # Include wheel for building distributions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist/*

close_pull_request_job:
  if: github.event_name == 'pull_request'
  runs-on: ubuntu-latest
  name: Handle Closed Pull Request
  steps:
    - name: Check PR Status
      id: check_pr_status
      run: |
        echo "Checking PR status..."
        if [[ "${{ github.event.action }}" == "closed" ]]; then
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR was merged."
            echo "PR_MERGED=true" >> $GITHUB_ENV
          else
            echo "PR was closed without merging."
            echo "PR_MERGED=false" >> $GITHUB_ENV
          fi
        else
          echo "PR is not closed. No action required."
          echo "PR_CLOSED=false" >> $GITHUB_ENV
        fi

    - name: Perform Actions for Merged PR
      if: env.PR_MERGED == 'true'
      run: |
        echo "Performing actions for merged PR..."
        # Your actions for a merged PR here

    - name: Perform Actions for Closed but Not Merged PR
      if: env.PR_MERGED == 'false'
      run: |
        echo "Performing actions for PR closed without merge."
        # Your actions for a closed but not merged PR here

    - name: No Action Needed
      if: env.PR_CLOSED == 'false'
      run: |
        echo "PR is not closed. This job does nothing but ensures no skipped status."

