close_pull_request_job:
  if: github.event_name == 'pull_request'
  runs-on: ubuntu-latest
  name: Handle Closed Pull Request
  steps:
    - name: Check PR Status
      id: check_pr_status
      run: |
        echo "Checking PR status..."
        if [[ "${{ github.event.action }}" == "closed" ]]; then
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR was merged."
            echo "PR_MERGED=true" >> $GITHUB_ENV
          else
            echo "PR was closed without merging."
            echo "PR_MERGED=false" >> $GITHUB_ENV
          fi
        else
          echo "PR is not closed. No action required."
          echo "PR_CLOSED=false" >> $GITHUB_ENV
        fi

    - name: Perform Actions for Merged PR
      if: env.PR_MERGED == 'true'
      run: |
        echo "Performing actions for merged PR..."
        # Your actions for a merged PR here

    - name: Perform Actions for Closed but Not Merged PR
      if: env.PR_MERGED == 'false'
      run: |
        echo "Performing actions for PR closed without merge."
        # Your actions for a closed but not merged PR here

    - name: No Action Needed
      if: env.PR_CLOSED == 'false'
      run: |
        echo "PR is not closed. This job does nothing but ensures no skipped status."
