name: Build Artifacts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest wheel  # Include wheel for building distributions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist/*

  close_pull_request_job:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Check Pull Request State
        id: check_state
        run: |
          if [[ "${{ github.event.action }}" == "closed" ]]; then
            echo "PR_CLOSED=true" >> $GITHUB_ENV
          else
            echo "PR_CLOSED=false" >> $GITHUB_ENV
          fi
      - name: Echo Close Pull Request
        if: env.PR_CLOSED == 'true'
        run: echo "Emulating closing the webapp link."
      - name: Handle Not Closed Pull Request
        if: env.PR_CLOSED == 'false'
        run: echo "Pull request is not closed. Exiting successfully."
