name: Create Version Tag

on:
  pull_request:
    types: [closed]

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set tag
        id: set_tag
        run: |
          # Get the current date
          DATE=$(date +%Y%m%d)
          # Get the pull request ID
          PR_ID=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          # Create the version tag
          VERSION_TAG="v${DATE}-${PR_ID}"
          echo "::set-output name=tag::$VERSION_TAG"
      
      - name: Create git tag
        if: github.event.pull_request.merged == true
        run: git tag ${{ steps.set_tag.outputs.tag }}
      
      - name: Push tag to repository
        if: github.event.pull_request.merged == true
        run: git push origin ${{ steps.set_tag.outputs.tag }}
