name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: read-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: freeedcom/ai-codereviewer@v2.7.0
        id: ai-review
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4-turbo-2024-04-09"
          exclude: "**/*.json, **/*.md"

      - name: Check for Comments and Fail if Found
        run: |
          # Assuming the AI Reviewer sets a flag in outputs if a comment is made
          if [[ "${{ steps.ai-review.outputs.comment_made }}" == "true" ]]; then
            echo "Comment was made due to code issues."
            exit 1
          fi
